### ISSUE TITLE
[Question or Request Feature] RDS Aurora module

### ISSUE THREAD

**Issue by oanhnn** [cfn-modules/docs#22]
How to make a RDS Aurora with MySQL compatibility?
I have not found a case or document about this. I think we need a module do this.

**Comment by oanhnn** [comment]
I want donate a project about this feature.
What do i can?

**Comment by andreaswittig** [comment]
Thanks for raising this feature request. Would you please contact us at [hello@widdix.net](mailto:hello@widdix.net) to discuss how to sponsor this feature?

**Comment by michaelwittig** [comment]
no feedback
